---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: deployToBluemix
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: maven
    script: |-
      #!/bin/bash
      mvn -B package -Pwlp-download
    enable_tests: true
    test_file_pattern: 12-factor-application/target/test-reports/unit/TEST-*.xml
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      application: sample-microservices-12factorapp
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared CloudantDBFor12Factor
      cf push "${CF_APP}" -p 12-factor-application/target/12FactorAppServer.zip -f ./src/main/resources/
